### PR TITLE
improve xmake build and fix msvc bugs

### LINKED ISSUE #30: Usage of variadic macros is imcompatiable with msvc
### Search before asking

- [x] I searched the [issues](https://github.com/PikachuHy/pscm/issues) and found no similar issues.

### What happened + What you expected to happen
When I compile pscm with msvc, I gathered such warning:
```
include\pscm/Logger.h(3): error C2010: “.”: 宏参数表中的意外
include\pscm/Logger.h(10): error C2010: “.”: 宏参数表中的意外
include\pscm/Logger.h(11): error C2010: “.”: 宏参数表中的意外
include\pscm/Logger.h(12): error C2010: “.”: 宏参数表中的意外
include\pscm/Logger.h(13): error C2010: “.”: 宏参数表中的意外
include\pscm/Logger.h(14): error C2010: “.”: 宏参数表中的意外
include\pscm/Logger.h(15): error C2010: “.”: 宏参数表中的意外
```
Reason of compilation failure is that [macro definitions at `include/pscm/Logger.h`](https://github.com/PikachuHy/pscm/blob/7b5c56102a8b3d4faedcfb546ae68e6a704b45a1/include/pscm/Logger.h#L10-L15) uses non-standard syntax of variadic macro.

### Anything else
* https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html
* https://en.cppreference.com/w/cpp/preprocessor/replace

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jingkaimori**
## Why

* Closes #30 
* Fix `ERROR` macro conflict on msvc
* Improve xmake config to avoid using submodules in `3rd/*`
* Xmake experimental support for C++20 modules

### CODE REVIEW

**Comment by PikachuHy** [comment]
the xmake ci is broken

https://github.com/PikachuHy/pscm/actions/runs/5811126226/job/15753620920?pr=31

**Comment by jingkaimori** [comment]
Waiting for xmake 2.8.2 and upgrade xmake to avoid clang error

**Comment by PikachuHy** [comment]
Great
thanks

**Comment by PikachuHy** [comment]
LGTM

**Pull request merged**
